"""
    Lebensmittelwarnungen API

    Liste aller Lebensmittel und Produktwarnungen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.lebensmittelwarnung.model.response_docs_inner_product import (
    ResponseDocsInnerProduct,
)
from deutschland.lebensmittelwarnung.model.response_docs_inner_rapex_information import (
    ResponseDocsInnerRapexInformation,
)
from deutschland.lebensmittelwarnung.model.response_docs_inner_safety_information import (
    ResponseDocsInnerSafetyInformation,
)

from deutschland import lebensmittelwarnung

globals()["ResponseDocsInnerProduct"] = ResponseDocsInnerProduct
globals()["ResponseDocsInnerRapexInformation"] = ResponseDocsInnerRapexInformation
globals()["ResponseDocsInnerSafetyInformation"] = ResponseDocsInnerSafetyInformation
from deutschland.lebensmittelwarnung.model.response_docs_inner import ResponseDocsInner


class TestResponseDocsInner(unittest.TestCase):
    """ResponseDocsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseDocsInner(self):
        """Test ResponseDocsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResponseDocsInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
