"""
    Lebensmittelwarnungen API

    Liste aller Lebensmittel und Produktwarnungen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.lebensmittelwarnung.model.response_product import ResponseProduct

from deutschland import lebensmittelwarnung


class TestResponseProduct(unittest.TestCase):
    """ResponseProduct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseProduct(self):
        """Test ResponseProduct"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResponseProduct()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
