"""
    Lebensmittelwarnungen API

    Liste aller Lebensmittel und Produktwarnungen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.lebensmittelwarnung.model.response_docs_inner_rapex_information import (
    ResponseDocsInnerRapexInformation,
)

from deutschland import lebensmittelwarnung


class TestResponseDocsInnerRapexInformation(unittest.TestCase):
    """ResponseDocsInnerRapexInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseDocsInnerRapexInformation(self):
        """Test ResponseDocsInnerRapexInformation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResponseDocsInnerRapexInformation()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
