"""
    Lebensmittelwarnungen API

    Liste aller Lebensmittel und Produktwarnungen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.lebensmittelwarnung.model.response_docs_inner_safety_information import (
    ResponseDocsInnerSafetyInformation,
)

from deutschland import lebensmittelwarnung


class TestResponseDocsInnerSafetyInformation(unittest.TestCase):
    """ResponseDocsInnerSafetyInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseDocsInnerSafetyInformation(self):
        """Test ResponseDocsInnerSafetyInformation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResponseDocsInnerSafetyInformation()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
