"""
    Lebensmittelwarnungen API

    Liste aller Lebensmittel und Produktwarnungen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.lebensmittelwarnung.model.response_product import ResponseProduct
from deutschland.lebensmittelwarnung.model.response_rapex_information import (
    ResponseRapexInformation,
)
from deutschland.lebensmittelwarnung.model.response_safety_information import (
    ResponseSafetyInformation,
)

from deutschland import lebensmittelwarnung

globals()["ResponseProduct"] = ResponseProduct
globals()["ResponseRapexInformation"] = ResponseRapexInformation
globals()["ResponseSafetyInformation"] = ResponseSafetyInformation
from deutschland.lebensmittelwarnung.model.response_docs import ResponseDocs


class TestResponseDocs(unittest.TestCase):
    """ResponseDocs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseDocs(self):
        """Test ResponseDocs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResponseDocs()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
