"""
    Lebensmittelwarnungen API

    Liste aller Lebensmittel und Produktwarnungen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.lebensmittelwarnung.model.request_options import RequestOptions

from deutschland import lebensmittelwarnung

globals()["RequestOptions"] = RequestOptions
from deutschland.lebensmittelwarnung.model.inline_object import InlineObject


class TestInlineObject(unittest.TestCase):
    """InlineObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject(self):
        """Test InlineObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineObject()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
