"""
    Lebensmittelwarnungen API

    Liste aller Lebensmittel und Produktwarnungen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.lebensmittelwarnung.model.response_safety_information import (
    ResponseSafetyInformation,
)

from deutschland import lebensmittelwarnung


class TestResponseSafetyInformation(unittest.TestCase):
    """ResponseSafetyInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseSafetyInformation(self):
        """Test ResponseSafetyInformation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResponseSafetyInformation()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
