"""
    Lebensmittelwarnungen API

    Liste aller Lebensmittel und Produktwarnungen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.lebensmittelwarnung.model.response_docs_inner_product import (
    ResponseDocsInnerProduct,
)

from deutschland import lebensmittelwarnung


class TestResponseDocsInnerProduct(unittest.TestCase):
    """ResponseDocsInnerProduct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseDocsInnerProduct(self):
        """Test ResponseDocsInnerProduct"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResponseDocsInnerProduct()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
