"""
    Lebensmittelwarnungen API

    Liste aller Lebensmittel und Produktwarnungen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.lebensmittelwarnung.api.default_api import DefaultApi  # noqa: E501

from deutschland import lebensmittelwarnung


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_warnungen(self):
        """Test case for list_warnungen

        Liste aller Lebensmittel und Produktwarnungen  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
